
---

  - name: Copying UChiwa config file
    template:
      src: ./templates/uchiwa/uchiwa.json.j2
      dest: /etc/sensu/uchiwa.json
      owner: sensu
      group: sensu
      mode: 0640
    notify: Restart UChiwa server

  - name: Starting UChiwa
    systemd:
      name: uchiwa
      state: started
      enabled: yes

