
---

  - name: Creating directories
    file:
      path: /etc/sensu/conf.d/{{ item.path }}
      state: directory
      mode: 0750
      owner: sensu
      group: sensu
    with_filetree: ./templates/sensu/
    when: item.state == 'directory'

  - name: Copying Sensu config files
    template:
      src: "{{ item.src }}"
      dest: /etc/sensu/conf.d/{{ item.path|dirname }}/{{ item.path|basename|regex_replace('\.j2','') }}
      owner: sensu
      group: sensu
      mode: 0640
    with_filetree: ./templates/sensu/
    when: item.state == 'file'
    notify: Restart Sensu server

  - name: Copying Sensu commandline tool
    template:
      src: ./templates/scripts/sensu-cli-dashboard.j2
      dest: /usr/local/bin/sensu-cli-dashboard
      owner: root
      group: root
      mode: 0755

  - name: Starting Sensu server
    systemd:
      name: sensu-server
      state: started
      enabled: yes

  - name: Starting Sensu API
    systemd:
      name: sensu-api
      state: started
      enabled: yes


