 
---

  - name: Copying Sensu commandline tool
    template:
      src: ./templates/scripts/sensu-cli-dashboard.j2
      dest: /usr/local/bin/sensu-cli-dashboard
      owner: root
      group: root
      mode: 0755

  - name: Copying Sensu extensions
    template:
      src: ./templates/sensu/extensions/elastic.rb.j2
      dest: /etc/sensu/extensions/elastic.rb
      owner: sensu
      group: sensu
      mode: 0644

