 
---

  - name: Copying Sensu commandline tool
    template:
      src: ./templates/scripts/sensu-cli-dashboard.j2
      dest: /usr/local/bin/sensu-cli-dashboard
      owner: root
      group: root
      mode: 0755



