
---

  - name: Installing the Sensu RPM file
    zypper:
      name: /var/tmp/{{ rpm_sensu }}
      disable_gpg_check: yes
      state: present

  - name: Copying systemd service files
    template:
      src: '{{ item.src }}'
      dest: /lib/systemd/system/{{ item.path|basename|regex_replace('\.j2','') }}
      owner: root
      group: root
      mode: 0640
    with_filetree: ./templates/systemd/
    when: item.state == 'file'


